on:
  push:
    branches:
      - master
    paths:
      - 'package.json'
      - 'tests/**'
      - 'src/**'
  pull_request:
    paths:
      - 'package.json'
      - 'tests/**'
      - 'src/**'

name: Run tests

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Restore the node modules
      uses: actions/cache@v4
      with:
        path: '**/node_modules'
        key: modules-${{ hashFiles('**/package.json') }}

    - name: Restore the files 
      uses: actions/cache@v4
      with:
        path: '**/files'
        key: files-${{ hashFiles('**/package.json') }}

    - name: Install packages
      run: npm i --include-dev

    - name: Run tests
      run: npm run test
